# Generated by Django 5.2.8 on 2025-12-02 12:14

import django.db.models.functions.comparison
from django.db import migrations, models

import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('author', models.CharField(max_length=255, verbose_name='著者')),
                ('selled_year', models.PositiveIntegerField(verbose_name='発売年')),
                ('selled_month', models.PositiveIntegerField(verbose_name='発売月')),
                ('selled_date', models.GeneratedField(db_persist=True, expression=web.models.MakeDate(django.db.models.functions.comparison.Cast(models.F('selled_year'), models.IntegerField()), django.db.models.functions.comparison.Cast(models.F('selled_month'), models.IntegerField()), models.Value(1)), output_field=models.DateField())),
            ],
            options={
                'verbose_name': '本',
                'verbose_name_plural': '本',
            },
        ),
    ]
